version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:10
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRESQL_URL=${POSTGRESQL_URL}
    ports:
      - '3000:3000'
    environment:
      POSTGRESQL_URL: ${POSTGRESQL_URL}
volumes:
  postgres: ~
