version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:10
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  prisma-lift:
    container_name: prisma-lift
    build:
      context: prisma
      dockerfile: Dockerfile
    environment:
      POSTGRESQL_URL: ${POSTGRESQL_URL}
volumes:
  postgres: ~
